import type { Machine } from "./machines";

export const backZone = {
  title: "Dorso",
  eyebrow: "Allenamento per zona · Schiena",
  heroTitle: ["COSTRUISCI", "IL TUO", "DORSO."],
  heroLead: "Dieci postazioni dedicate alla schiena: trazioni verticali, rematori, pullover, T-Bar, lavoro lombare e una stazione per shrug e deadlift. Esplora l’area e apri la scheda della macchina che vuoi conoscere.",
  manifestoTitle: ["AMPIEZZA E SPESSORE.", "SENZA COMPROMESSI."],
  manifesto: [
    "Un dorso completo richiede più di una sola tirata. Servono traiettorie verticali per l’ampiezza, rematori per lo spessore, lavoro a bracci indipendenti e strumenti capaci di allenare anche trapezi, erettori spinali e controllo scapolare.",
    "L’area dorso di Revenge Gym combina macchine selectorized, plate loaded e postazioni libere: Precor, Life Fitness, Technogym e soluzioni specialistiche che permettono di scegliere presa, angolo e curva di resistenza in base all’obiettivo.",
    "Ogni scheda raccoglie funzione, muscoli coinvolti, regolazione, programmazione ed errori comuni. Il carico conta, ma soltanto quando la schiena guida il gesto e ogni ripetizione resta leggibile.",
  ],
};

export const backMachines: Machine[] = [
  {
    id: "easy-power-station-precor", number: "01", name: "Easy Power Station", brand: "Precor", category: "Trazioni assistite", image: "/photos/machines/dorso/easy-power-station-precor.webp", alt: "Easy Power Station Precor per trazioni assistite nella sala Revenge Gym", tagline: "Trazioni e dip assistiti con progressione misurabile.",
    brandNote: ["La Easy Power Station Precor è una stazione assistita che utilizza il pacco pesi come contrappeso: più assistenza viene selezionata, minore è la quota di peso corporeo da sollevare.", "Le impugnature multiple permettono di lavorare sulle trazioni con prese diverse e di costruire gradualmente forza nel gesto a corpo libero."],
    lead: ["Sali sulla pedana o sull’appoggio mobile in modo controllato, scegli una presa stabile e avvia la trazione abbassando le scapole prima di flettere i gomiti.", "Porta il petto verso l’alto senza cercare il mento a ogni costo; ritorna fino a un allungamento gestibile, mantenendo spalle e tronco sotto controllo."],
    qualityEdge: "L’assistenza regolabile rende la trazione accessibile e progressiva senza trasformarla in un movimento diverso: uno strumento utile dal primo approccio fino alle serie tecniche avanzate.", focus: "Progressione nelle trazioni verticali", primaryMuscles: ["Grande dorsale", "Grande rotondo", "Bicipite brachiale"], secondaryMuscles: ["Trapezio medio e inferiore", "Romboidi", "Core"],
    trainingRole: ["Apprendimento e progressione della trazione", "Serie tecniche a ripetizioni controllate", "Lavoro verticale con assistenza scalabile"], cues: ["Scapole verso il basso prima dei gomiti", "Petto aperto e costole controllate", "Niente slancio delle gambe", "Ritorno lento senza crollare sulle spalle"], programming: ["Tecnica: 4×5–8 con assistenza moderata", "Ipertrofia: 3–4×8–12", "Progressione: riduci gradualmente l’assistenza"], errors: ["Confondere più peso selezionato con maggiore difficoltà", "Tirare soltanto con le braccia", "Oscillare con il bacino", "Perdere il controllo in discesa"], trainer: "Usa l’assistenza per rendere ogni ripetizione migliore, non soltanto più facile. Quando la scapola parte bene, il dorsale entra davvero nel gesto."
  },
  {
    id: "lat-machine-precor", number: "02", name: "Lat Machine", brand: "Precor", category: "Trazione verticale", image: "/photos/machines/dorso/lat-machine-precor.webp", alt: "Lat Machine Precor con barra larga nella sala Revenge Gym", tagline: "Trazione verticale classica, stabile e regolabile.",
    brandNote: ["La Lat Machine Precor è una postazione selectorized dedicata alle tirate dall’alto, con pacco pesi e barra larga per una regolazione rapida e replicabile.", "La struttura guidata permette di concentrarsi sulla traiettoria dei gomiti e sul lavoro del dorso senza dover stabilizzare il corpo come in una trazione libera."],
    lead: ["Blocca le cosce sotto i rulli, afferra la barra con una presa confortevole e inclina appena il busto mantenendo il torace alto.", "Tira la barra verso la parte alta del petto guidando i gomiti verso il basso; risali senza perdere la posizione delle costole e senza lasciare cadere il pacco pesi."],
    qualityEdge: "Una lat machine ben impostata offre una progressione chiara per ampiezza e forza del dorso, con carichi facilmente confrontabili nel tempo.", focus: "Ampiezza del dorso e forza in tirata", primaryMuscles: ["Grande dorsale", "Grande rotondo"], secondaryMuscles: ["Bicipite brachiale", "Romboidi", "Trapezio inferiore"], trainingRole: ["Trazione verticale principale", "Alternativa o complemento alle trazioni", "Volume controllato per il dorsale"], cues: ["Cosce ferme sotto i rulli", "Gomiti verso il basso", "Barra davanti al corpo", "Eccentrica completa e controllata"], programming: ["Forza-ipertrofia: 4×6–10", "Ipertrofia: 3–4×8–12", "Volume: 3×12–15"], errors: ["Tirare dietro la nuca", "Dondolare il busto", "Chiudere le spalle in avanti", "Rimbalzare il pacco pesi"], trainer: "La barra scende perché i gomiti vanno verso il pavimento. Se pensi soltanto alle mani, saranno le braccia a rubare il lavoro."
  },
  {
    id: "lateral-front-lat-pulldown", number: "03", name: "Lateral Front Lat Pulldown", brand: "Plate Loaded", category: "Trazione verticale", image: "/photos/machines/dorso/lateral-front-lat-pulldown.webp", alt: "Lateral Front Lat Pulldown plate loaded arancione nella sala Revenge Gym", tagline: "Leve indipendenti e tirata frontale caricata a dischi.",
    brandNote: ["La Lateral Front Lat Pulldown è una macchina plate loaded con leve indipendenti e appoggio per le cosce, progettata per una trazione verticale convergente.", "Il caricamento a dischi restituisce una sensazione diretta e consente di controllare separatamente i due lati, senza attribuire alla macchina un marchio non visibile."],
    lead: ["Regola seduta e fermacosce, scegli le impugnature e parti con braccia distese ma spalle controllate. Porta i gomiti verso i fianchi seguendo la curva naturale delle leve.", "Puoi lavorare bilateralmente oppure un lato alla volta, evitando rotazioni del tronco e mantenendo il bacino stabile sulla seduta."],
    qualityEdge: "Le leve indipendenti aggiungono una variante reale alla tirata verticale e rendono evidenti eventuali differenze di controllo tra destra e sinistra.", focus: "Trazione verticale indipendente", primaryMuscles: ["Grande dorsale", "Grande rotondo"], secondaryMuscles: ["Bicipite brachiale", "Romboidi", "Deltoide posteriore"], trainingRole: ["Tirata principale plate loaded", "Lavoro unilaterale", "Progressione a dischi per ampiezza e forza"], cues: ["Blocca bene le cosce", "Porta i gomiti ai fianchi", "Mantieni il torace composto", "Controlla entrambe le leve"], programming: ["Carico: 4×6–10", "Ipertrofia: 3–4×8–12", "Unilaterale: 3×10–12 per lato"], errors: ["Carichi diversi sulle leve", "Strappare dalla posizione alta", "Ruotare il busto", "Accorciare l’allungamento"], trainer: "Non inseguire i dischi: segui la traiettoria delle leve e fai arrivare i gomiti vicino ai fianchi senza perdere il tronco."
  },
  {
    id: "linear-row", number: "04", name: "Linear Row", brand: "Plate Loaded", category: "Rematore orizzontale", image: "/photos/machines/dorso/linear-row.webp", alt: "Linear Row plate loaded nera nella sala Revenge Gym", tagline: "Rematore sostenuto, prese multiple e bracci indipendenti.",
    brandNote: ["La Linear Row è un rematore plate loaded con appoggio toracico, pedana ampia e bracci indipendenti. La macchina fotografata offre più impugnature per variare la posizione di mani e gomiti.", "L’appoggio del petto limita lo slancio e permette di concentrare il lavoro sul dorso, mantenendo la zona lombare meno coinvolta rispetto a un rematore libero."],
    lead: ["Regola la posizione affinché il torace appoggi saldamente al cuscino e le maniglie siano raggiungibili senza arrotondare le spalle.", "Tira portando i gomiti indietro lungo la linea scelta, poi lascia avanzare le scapole con controllo senza staccare il petto dal supporto."],
    qualityEdge: "Prese multiple, leve indipendenti e sostegno toracico rendono questa row precisa, intensa e adattabile a obiettivi diversi.", focus: "Spessore del dorso con busto sostenuto", primaryMuscles: ["Grande dorsale", "Romboidi", "Trapezio medio"], secondaryMuscles: ["Deltoide posteriore", "Bicipite brachiale", "Grande rotondo"], trainingRole: ["Rematore principale pesante", "Lavoro di spessore", "Tirata unilaterale o bilaterale"], cues: ["Petto sempre sul cuscino", "Polsi neutri", "Gomiti guidano il movimento", "Allunga senza perdere controllo scapolare"], programming: ["Forza-ipertrofia: 4×6–10", "Ipertrofia: 3–4×8–12", "Unilaterale: 3×10 per lato"], errors: ["Staccare il torace", "Stringere le spalle verso le orecchie", "Accorciare il ritorno", "Caricare i lati in modo diverso"], trainer: "Il supporto toracico elimina molte scuse: tienilo fermo e lascia che siano scapole e gomiti a costruire ogni centimetro della tirata."
  },
  {
    id: "panca-iperextension", number: "05", name: "Panca Iperextension", brand: "45° Bench", category: "Catena posteriore", image: "/photos/machines/dorso/panca-iperextension.webp", alt: "Panca per iperestensioni a 45 gradi nella sala Revenge Gym", tagline: "Controllo lombare, anche forti e catena posteriore.",
    brandNote: ["La panca per iperestensioni a 45° sostiene cosce e caviglie lasciando libero il movimento dell’anca. È una postazione semplice, ma estremamente utile quando viene regolata e usata con precisione.", "L’altezza dei cuscini deve consentire al bacino di flettersi senza comprimere l’addome e senza trasformare l’esercizio in un movimento casuale della colonna."],
    lead: ["Posiziona il bordo dei cuscini poco sotto le anche, blocca bene i piedi e scendi mantenendo la colonna lunga. Risali estendendo le anche fino alla linea del corpo.", "Per enfatizzare glutei e femorali pensa a spingere il bacino nei cuscini; per il controllo lombare usa carico moderato e ritmo lento."],
    qualityEdge: "Una catena posteriore forte completa il lavoro del dorso e migliora la capacità di mantenere assetto nelle tirate e negli esercizi liberi.", focus: "Erettori spinali e catena posteriore", primaryMuscles: ["Erettori spinali", "Grande gluteo", "Ischiocrurali"], secondaryMuscles: ["Adduttori", "Core profondo"], trainingRole: ["Rinforzo lombare controllato", "Complemento a rematori e stacchi", "Lavoro di resistenza della catena posteriore"], cues: ["Cuscini sotto la piega dell’anca", "Colonna lunga", "Movimento guidato dalle anche", "Fermati sulla linea del corpo"], programming: ["Controllo: 3×10–15", "Resistenza: 3×15–20", "Con sovraccarico: 3×8–12 per esperti"], errors: ["Iperestendere oltre la linea del corpo", "Cuscini troppo alti", "Rimbalzare in basso", "Usare un disco prima di controllare il corpo"], trainer: "Il nome non autorizza a iperestendere la schiena: arriva in linea, stringi glutei e mantieni la ripetizione pulita."
  },
  {
    id: "pulley-linea-lux-technogym", number: "06", name: "Pulley Linea Lux", brand: "Technogym", category: "Rematore al cavo", image: "/photos/machines/dorso/pulley-linea-lux-technogym.webp", alt: "Pulley Linea Lux Technogym nella sala Revenge Gym", tagline: "Tensione continua e libertà di presa nel rematore basso.",
    brandNote: ["Il Pulley della linea Lux Technogym è una postazione a cavo basso con pacco pesi, pedane e panca lunga, pensata per il rematore seduto.", "Il cavo consente di cambiare impugnatura e mantiene tensione lungo tutta la corsa, offrendo una sensazione diversa dalle leve rigide delle row plate loaded."],
    lead: ["Siediti con piedi saldi alle pedane, ginocchia leggermente flesse e busto alto. Porta l’impugnatura verso l’addome guidando indietro i gomiti.", "Lascia avanzare le scapole nel ritorno senza collassare con la zona lombare; il busto può accompagnare appena, ma non deve oscillare per spostare il carico."],
    qualityEdge: "Il pulley completa i rematori a leva con una tirata fluida, modulabile e compatibile con numerose impugnature.", focus: "Rematore basso a tensione continua", primaryMuscles: ["Grande dorsale", "Romboidi", "Trapezio medio"], secondaryMuscles: ["Bicipite brachiale", "Deltoide posteriore", "Erettori spinali"], trainingRole: ["Rematore orizzontale principale o complementare", "Volume tecnico", "Variazioni di presa al cavo"], cues: ["Piedi saldi", "Torace alto", "Tira verso l’addome", "Ritorno con scapole controllate"], programming: ["Ipertrofia: 3–4×8–12", "Volume: 3×12–15", "Pausa in chiusura: 3×10"], errors: ["Dondolare avanti e indietro", "Tirare verso il petto alto", "Spalle sollevate", "Pacco pesi che rimbalza"], trainer: "Lascia che le scapole si muovano, ma non consegnare il movimento alla zona lombare. Il cavo deve restare teso e il busto leggibile."
  },
  {
    id: "pullover-plate-loaded", number: "07", name: "Pullover Machine", brand: "Plate Loaded", category: "Estensione di spalla", image: "/photos/machines/dorso/pullover-plate-loaded.webp", alt: "Pullover Machine plate loaded arancione nella sala Revenge Gym", tagline: "Dorsale sotto tensione senza dipendere dalla presa.",
    brandNote: ["La Pullover Machine plate loaded utilizza ampi cuscini per i gomiti e una leva caricata a dischi per allenare l’estensione della spalla.", "L’appoggio sugli avambracci riduce la dipendenza da presa e flessori del gomito, permettendo di concentrare l’intenzione sul grande dorsale."],
    lead: ["Regola la seduta e appoggia i gomiti ai cuscini con il busto stabile. Porta la leva dall’alto verso il basso descrivendo un arco controllato.", "Mantieni le costole composte ed evita di trasformare la chiusura in un’estensione lombare; ritorna fin dove la spalla resta confortevole."],
    qualityEdge: "Il pullover offre un pattern diverso da lat machine e rematori: isola l’estensione della spalla e amplia davvero il catalogo dorso.", focus: "Isolamento del grande dorsale", primaryMuscles: ["Grande dorsale", "Grande rotondo"], secondaryMuscles: ["Capo lungo del tricipite", "Dentato anteriore", "Core"], trainingRole: ["Pre-attivazione del dorsale", "Complemento dopo le tirate", "Finisher a tensione continua"], cues: ["Gomiti saldi sui cuscini", "Costole controllate", "Spingi la leva con il dorsale", "Allungamento senza forzare la spalla"], programming: ["Ipertrofia: 3–4×8–12", "Controllo: 3×12–15", "Finisher: 2×15–20"], errors: ["Inarcare la zona lombare", "Perdere il contatto dei gomiti", "Caricare oltre l’escursione utile", "Rimbalzare in alto"], trainer: "Pensa a portare i gomiti verso i fianchi mantenendo il tronco fermo. Se si muovono le costole, il dorsale sta perdendo il suo vantaggio."
  },
  {
    id: "seated-row-life-fitness", number: "08", name: "Seated Row", brand: "Life Fitness", category: "Rematore guidato", image: "/photos/machines/dorso/seated-row-life-fitness.webp", alt: "Seated Row Life Fitness nella sala Revenge Gym", tagline: "Rematore selectorized stabile con appoggio toracico.",
    brandNote: ["La Seated Row Life Fitness combina pacco pesi, seduta regolabile, appoggio toracico e leve guidate per una tirata orizzontale stabile.", "Le impugnature consentono una presa naturale, mentre il supporto del torace aiuta a limitare compensi e slanci durante le serie vicine alla fatica."],
    lead: ["Regola la seduta affinché il cuscino sostenga il centro del torace senza impedire il respiro. Afferra le maniglie con braccia distese e spalle controllate.", "Tira i gomiti indietro, chiudi le scapole senza sollevare le spalle e ritorna lentamente fino a recuperare lunghezza nel dorso."],
    qualityEdge: "La selectorized Life Fitness rende semplice replicare regolazioni e carichi, qualità essenziale per misurare una progressione reale.", focus: "Spessore del dorso con appoggio toracico", primaryMuscles: ["Romboidi", "Trapezio medio", "Grande dorsale"], secondaryMuscles: ["Bicipite brachiale", "Deltoide posteriore", "Grande rotondo"], trainingRole: ["Rematore principale guidato", "Volume vicino alla fatica", "Lavoro tecnico sulla retrazione scapolare"], cues: ["Torace sul cuscino", "Spalle basse", "Gomiti indietro senza strappo", "Ritorno completo"], programming: ["Forza-ipertrofia: 4×6–10", "Ipertrofia: 3–4×8–12", "Volume: 3×12–15"], errors: ["Staccare il petto", "Accorciare il ritorno", "Piegare i polsi", "Far sbattere il pacco pesi"], trainer: "Registra seduta e carico: la macchina ti offre una ripetibilità eccellente, ma devi presentarti ogni volta con lo stesso assetto."
  },
  {
    id: "t-bar-row", number: "09", name: "T-Bar Row", brand: "Plate Loaded", category: "Rematore libero guidato", image: "/photos/machines/dorso/t-bar-row.webp", alt: "T-Bar Row con appoggio toracico nella sala Revenge Gym", tagline: "Dischi, appoggio toracico e rematore di spessore.",
    brandNote: ["La T-Bar Row fotografata è una postazione plate loaded con pedana inclinata, supporto toracico e leva centrale caricata a dischi.", "L’appoggio riduce la richiesta alla zona lombare e permette di sviluppare una tirata potente mantenendo una traiettoria definita."],
    lead: ["Sali sulla pedana con piedi stabili e appoggia il torace al cuscino. Afferra la maniglia senza incurvare il collo e stacca il carico con controllo.", "Tira la leva verso il supporto guidando indietro i gomiti; scendi fino a distendere le braccia senza perdere l’appoggio e senza lasciare cadere i dischi."],
    qualityEdge: "Una T-Bar con sostegno toracico consente di caricare il rematore senza trasformarlo in una gara di compensi lombari.", focus: "Rematore pesante per lo spessore", primaryMuscles: ["Trapezio medio", "Romboidi", "Grande dorsale"], secondaryMuscles: ["Deltoide posteriore", "Bicipite brachiale", "Grande rotondo"], trainingRole: ["Rematore pesante della seduta", "Costruzione dello spessore", "Alternativa supportata al rematore con bilanciere"], cues: ["Piedi saldi sulla pedana", "Petto sempre sostenuto", "Collo neutro", "Gomiti indietro e discesa controllata"], programming: ["Forza-ipertrofia: 4×6–10", "Ipertrofia: 3×8–12", "Back-off: 2×12–15"], errors: ["Sollevare il torace", "Strappare il primo centimetro", "Caricare prima di trovare la presa", "Lasciare cadere la leva"], trainer: "La T-Bar premia il carico soltanto se il petto resta sul supporto. Se ti sollevi, stai cambiando esercizio e perdendo precisione."
  },
  {
    id: "trap-shrug-deadlift", number: "10", name: "Trap Shrug / Deadlift", brand: "Plate Loaded", category: "Trapezi e catena posteriore", image: "/photos/machines/dorso/trap-shrug-deadlift.webp", alt: "Trap Shrug e Deadlift machine plate loaded nella sala Revenge Gym", tagline: "Leve indipendenti per shrug, deadlift e tirate da terra.",
    brandNote: ["Questa stazione plate loaded dispone di due leve indipendenti, impugnature neutre e più punti di carico. La configurazione è adatta a shrug, varianti di deadlift e lunge, in base a posizione e tecnica.", "Non viene attribuito un marchio non leggibile: il valore della postazione è nella sua funzione, nella stabilità e nella possibilità di caricare i due lati in modo controllato."],
    lead: ["Per lo shrug afferra le maniglie, mantieni braccia lunghe e solleva le spalle verticalmente senza ruotarle. Per il deadlift crea tensione prima di spingere il pavimento e distendere anche e ginocchia insieme.", "Le due leve devono essere caricate in modo identico. Scegli l’esercizio prima del peso e verifica che la posizione di partenza sia compatibile con la tua mobilità."],
    qualityEdge: "Una sola struttura aggiunge lavoro specifico per trapezi e catena posteriore senza rinunciare a impugnature neutre e carico indipendente.", focus: "Trapezi, presa e catena posteriore", primaryMuscles: ["Trapezio superiore", "Grande gluteo", "Ischiocrurali"], secondaryMuscles: ["Erettori spinali", "Quadricipiti", "Avambracci"], trainingRole: ["Shrug pesante", "Variante guidata di deadlift", "Lavoro di presa e catena posteriore"], cues: ["Carica i lati allo stesso modo", "Braccia lunghe nello shrug", "Schiena neutra nel deadlift", "Chiudi con le anche, non iperestendere"], programming: ["Shrug: 4×8–12", "Deadlift tecnico: 4×5–8", "Presa e controllo: 3×10–12"], errors: ["Ruotare le spalle nello shrug", "Partire senza tensione", "Caricare i lati diversamente", "Iperestendere la schiena in chiusura"], trainer: "Questa macchina può fare più cose, ma una serie deve avere un solo obiettivo: scegli il gesto, costruisci l’assetto e poi aggiungi i dischi."
  },
];

export function getBackMachine(id: string) {
  return backMachines.find((machine) => machine.id === id);
}
